### ISSUE TITLE
Negative satoshis

### ISSUE THREAD

**Issue by DanielKrawisz** [pow-co/boostpow-button#3]
If you slide the satoshi slider all the way to the left, you get negative values. 

There needs to be a minimum value allowed for ANY boost because of tx fees. That minimum value should be about 50. There also needs to be a minimum profitability, which should be about 20,000. 

In the future, it would be good to try to adjust these values based on recent history but these should be good for now.

**Comment by 1aristotelis** [comment]
fixing this made me realize how bad i became at basic maths 😭
